# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-23 18:14
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(default='no phone', max_length=100)),
                ('address', models.CharField(default='no address', max_length=200)),
                ('website', models.URLField(default='www.I_Have_No_Website.none', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(default='Person', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('rating', models.CharField(choices=[('SU', 'Strongly Unrecommended'), ('UN', 'Unrecommended'), ('NE', 'Neutral'), ('RA', 'Recommended'), ('SR', 'Strongly Recommended')], default='NE', max_length=2)),
                ('comment', models.TextField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GLAM.Contact')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('last_review_timestamp', models.DateField(default=datetime.date.today)),
                ('last_database_add', models.DateField(default=datetime.date.today)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GLAM.Nation')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_dispatch', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(default='contacted via standard html email', max_length=1000)),
                ('reply', models.BooleanField(default=False)),
                ('via_phone_contact', models.BooleanField(default=False)),
                ('via_social_contact', models.BooleanField(default=False)),
                ('via_email_contact', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GLAM.Contact')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GLAM.ContactType'),
        ),
        migrations.AddField(
            model_name='contact',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contact',
            name='nation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GLAM.Nation'),
        ),
        migrations.AddField(
            model_name='contact',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GLAM.Region'),
        ),
    ]
